name: Auto run
on:
  workflow_dispatch:
  schedule:
    - cron: '5 8,10 * * 1,2,4,5'
    - cron: '5 13 * * 2'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          UNIGE_USERNAME: ${{ secrets.UNIGE_USERNAME }}
          UNIGE_PASSWORD: ${{ secrets.UNIGE_PASSWORD }}
